### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ada#23]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/ada/issues/14)
- [ ] [Add key features](https://github.com/exercism/ada/issues/15)
- [ ] [Add tags](https://github.com/exercism/ada/issues/16)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/ada/issues/17)
- [ ] [Update status of track](https://github.com/exercism/ada/issues/21)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/ada/issues/22)
- [ ] [Pass linting checks](https://github.com/exercism/ada/issues/18)
- [ ] [Build Test Runner](https://github.com/exercism/ada/issues/19)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/ada/issues/20) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/ada/issues/26)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
